name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Build app
        run: vr build
      - name: Lint code
        run: vr lint
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Setup dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh && cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
      - name: Format code
        run: dprint check --config .github/config/dprint.json
  test:
    name: Test code
    runs-on: ${{ matrix.os }}
    needs:
      - lint
      - format
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Build app
        run: vr build
      - name: Create itsudeno directory
        run: mkdir .itsudeno
      - name: Run tests
        run: vr test
  codeql:
    name: Analyze code
    runs-on: ubuntu-latest
    needs:
      - lint
      - format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
          config-file: .github/config/codeql.yml
      - name: Analyze code
        uses: github/codeql-action/analyze@v1
  publish:
    name: Publish generated files
    runs-on: ubuntu-latest
    needs:
      - test
      - codeql
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1
      - name: Setup dprint
        run: curl -fsSL https://dprint.dev/install.sh | sh && cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
      - name: Generate files
        run: |
          git checkout main
          vr build
          vr lock
          vr fmt
      - name: Publish generated files
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "ci: update generated files" && git push)