name: Label issues and pull requests

on: pull_request_target

jobs:
  labeler:
    name: Label issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ github.token }}"
          configuration-path: .github/config/labels.yml
          sync-labels: yes